Repository Recoded-Spark-Turkey-2022/Venus, pull requests merged in 2023-01, with the labels that each got.

#63 doc: improve in about section in home page and about page
  package.json
  src/assets/aboutUs.png
  src/components/UI/ContainAbout.jsx
  src/components/UI/CoverSection.jsx
  src/components/about/About.jsx
  src/components/about/about.css
  src/components/aboutPage/Cover.jsx
  src/components/aboutPage/Share.jsx
  src/components/aboutPage/cover.css
  src/pages/About.jsx
  src/pages/Home.jsx
  src/routes/AppRouter.jsx
  tailwind.config.js
  yarn.lock
Labels: documentation

#75 Doc,Style: add content and style about page
  src/Reference.css
  src/assets/shareStory.svg
  src/components/Reference.jsx
  src/components/StoryComponent.jsx
  src/components/UI/ReferenceSection.jsx
  src/components/about/About.jsx
  src/components/about/about.css
  src/components/aboutPage/Cover.jsx
  src/components/aboutPage/OurStory.jsx
  src/components/aboutPage/Share.jsx
  src/components/aboutPage/cover.css
  src/components/homePage/HeroSection.jsx
Labels: documentation, enhancement

#118 feat: warn message
  src/components/aboutPage/Share.jsx
  src/components/footer/Footer.jsx
  src/components/footer/__tests__/__snapshots__/footer.test.jsx.snap
  src/components/footer/__tests__/footer.test.jsx
  src/components/homePage/Hero.test.jsx
  src/components/homePage/HeroSection.jsx
  src/components/homePage/__snapshots__/Hero.test.jsx.snap
  src/components/navbar/__snapshots__/Navbar.test.jsx.snap
  src/components/singleBlog/__snapshots__/SingleBlog.test.jsx.snap
  src/pages/About.jsx
  src/pages/Home.jsx
  src/routes/AppRouter.jsx
Labels: enhancement

#126 adding test to about page
  src/components/aboutPage/__tests__/Cover.test.jsx
  src/components/aboutPage/__tests__/OurStory.test.jsx
  src/components/aboutPage/__tests__/OurTeamSection.test.jsx
  src/components/aboutPage/__tests__/Share.test.jsx
  src/components/aboutPage/__tests__/TeamMemberCard.test.jsx
  src/components/aboutPage/__tests__/TeamMembersNavigator.test.jsx
  src/components/aboutPage/__tests__/TeamNarButton.test.jsx
  src/components/aboutPage/__tests__/__snapshots__/Cover.test.jsx.snap
  src/components/aboutPage/__tests__/__snapshots__/OurStory.test.jsx.snap
  src/components/aboutPage/__tests__/__snapshots__/OurTeamSection.test.jsx.snap
  src/components/aboutPage/__tests__/__snapshots__/Share.test.jsx.snap
  src/components/aboutPage/__tests__/__snapshots__/TeamMemberCard.test.jsx.snap
  src/components/aboutPage/__tests__/__snapshots__/TeamMembersNavigator.test.jsx.snap
  src/components/aboutPage/__tests__/__snapshots__/TeamNarButton.test.jsx.snap
  src/components/navbar/__snapshots__/Navbar.test.jsx.snap
  src/components/singleBlog/__snapshots__/SingleBlog.test.jsx.snap
Labels: documentation
